name: Github Actions demo

on:
    push:
        branches: [ 'main' ]
        paths-ignore: [ '.github' ]
    pull_request:
        branches: [ 'main' ]
    schedule:
        - cron: '15 6 * * 0'
    workflow_dispatch:
   
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Output results
              run: |
                echo "Triggered by, ${{ github.event }}!"
                echo "Triggered by, ${{ github.ref }}!"
                echo "Listing all files in the repository:"
                ls -R .