name: Github Actions demo

on:
    push:
        branches: [ 'main' ]
        paths-ignore: [ '.github' ]
    pull_request:
        branches: [ 'main' ]
    schedule:
        - cron: '15 6 * * 0'
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy to'
                required: true
                type: environment
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Output results
              run: |
                echo "Triggered by, ${{ toJson(github.event) }}!"
                echo "Triggered by, ${{ toJson(github.ref) }}!"
                echo "Listing all files in the repository:"
                ls -R .

    Test:
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'workflow_dispatch' }}
        environment: Test
        needs: build
        steps:
            - name: Test
              run: |
                echo "Testing...!"
                sleep 15

    Load-Test:
        runs-on: ubuntu-latest
        environment: Load-Test
        if: ${{ github.event_name == 'workflow_dispatch' }}
        needs: build
        steps:
            - name: Test
              run: |
                echo "Testing...."
                sleep 15
    
    Production:
        runs-on: ubuntu-latest
        environment: Production
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'Production' }}  
        needs: [ Test, Load-Test ]
        steps:
            - name: Deploy to production
              run: |
                echo "Deployed to production!"  
                sleep 15
                